services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastapidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapidb"]
      interval: 3s
      timeout: 2s
      retries: 20

  api:
    build: .
    working_dir: /app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  pgdata:
